"""add trip interests

Revision ID: 80d02af35722
Revises: 4e4a7f4eb4b8
Create Date: 2026-08-17 15:59:23.841063
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '80d02af35722'
down_revision = '4e4a7f4eb4b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'interests')
    # ### end Alembic commands ###
