import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { getCountries, getCities, getCityPlaces } from "../api/catalog";
import { addFavorite, getFavorites, removeFavorite } from "../api/favorites";

export default function DestinationsPage() {
  const { token, isAuthenticated } = useAuth();
  const [countries, setCountries] = useState([]), [cities, setCities] = useState([]), [places, setPlaces] = useState([]), [country, setCountry] = useState(null), [city, setCity] = useState(null), [favorites, setFavorites] = useState(new Set()), [query, setQuery] = useState(""), [category, setCategory] = useState(""), [loading, setLoading] = useState(true), [updatingPlace, setUpdatingPlace] = useState(null);
  useEffect(() => { getCountries().then((data) => { setCountries(data); setCountry(data[0]?.id); }).finally(() => setLoading(false)); if (isAuthenticated) getFavorites(token).then((data) => setFavorites(new Set(data.map((favorite) => favorite.place_id)))); }, [token, isAuthenticated]);
  useEffect(() => { if (country) getCities(country).then((data) => { setCities(data); setCity(data[0] || null); }); }, [country]);
  useEffect(() => { if (city) getCityPlaces(city.id).then(setPlaces); }, [city]);
  const shown = useMemo(() => places.filter((place) => (!query || place.name.toLowerCase().includes(query.toLowerCase())) && (!category || place.category === category)), [places, query, category]);
  const categories = [...new Set(places.map((place) => place.category))];
  async function toggle(place) { if (!isAuthenticated || updatingPlace) return; setUpdatingPlace(place.id); const next = new Set(favorites); try { if (next.has(place.id)) { await removeFavorite(token, place.id); next.delete(place.id); } else { await addFavorite(token, place.id); next.add(place.id); } setFavorites(next); } finally { setUpdatingPlace(null); } }
  return <section className="section page destinations-page"><div className="container"><p className="eyebrow">Каталог</p><h1 className="page-title">Места для новых<br /><em>впечатлений</em></h1><div className="destinations-hero-art" aria-hidden="true"><span /><span /></div>{loading ? <div className="catalog-loading">Загружаем направления…</div> : <><div className="country-tabs">{countries.map((item) => <button className={country === item.id ? "country-tab country-tab--active" : "country-tab"} onClick={() => setCountry(item.id)} key={item.id}>{item.name}</button>)}</div><div className="catalog-toolbar"><div><p className="eyebrow">Города</p><h2>Выберите направление</h2></div><input className="catalog-search" placeholder="Поиск города или места" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="catalog-grid">{cities.filter((item) => !query || item.name.toLowerCase().includes(query.toLowerCase())).map((item) => <button className={city?.id === item.id ? "catalog-card catalog-card--selected" : "catalog-card"} onClick={() => setCity(item)} key={item.id}><img src={item.image_url} alt={item.name} /><div className="catalog-card__body"><span className="pill pill--dark">Город</span><h2>{item.name}</h2><p>{item.description}</p></div></button>)}</div>{city && <section className="places-section"><div className="section-heading"><div><p className="eyebrow">Достопримечательности</p><h2>{city.name}: что посмотреть</h2></div><Link className="text-link" to="/favorites">Избранное →</Link></div><div className="filter-row"><button className={!category ? "active" : ""} onClick={() => setCategory("")}>Все</button>{categories.map((item) => <button className={category === item ? "active" : ""} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div>{!shown.length ? <div className="empty-state">Ничего не найдено. <button className="text-link" onClick={() => { setQuery(""); setCategory(""); }}>Сбросить фильтры</button></div> : <div className="places-grid">{shown.map((place) => <article className="place-card" key={place.id}><img src={place.image_url} alt={place.name} /><button className={favorites.has(place.id) ? "favorite-button active" : "favorite-button"} onClick={() => toggle(place)} disabled={updatingPlace !== null} aria-label="Избранное">♥</button><div className="place-card__body"><span className="pill pill--dark">{place.category}</span><h3>{place.name}</h3><p>{place.description}</p></div></article>)}</div>}</section>}</>}</div></section>;
}
